<?xml version="1.0" encoding="utf-8"?><Database Name="DB_QLCHTL" Class="QL_CHTLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MSI\SQLEXPRESS;Initial Catalog=DB_QLCHTL;Persist Security Info=True;User ID=sa" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="DB_QLCHTLConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CART_PRODUCTS" Member="CART_PRODUCTs">
    <Type Name="CART_PRODUCT">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PRODUCT_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CART_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CART_CART_PRODUCT" Member="CART" ThisKey="CART_ID" OtherKey="CART_ID" Type="CART" IsForeignKey="true" />
      <Association Name="PRODUCT_CART_PRODUCT" Member="PRODUCT" ThisKey="PRODUCT_ID" OtherKey="PRODUCT_ID" Type="PRODUCT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CARTS" Member="CARTs">
    <Type Name="CART">
      <Column Name="CART_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CART_CART_PRODUCT" Member="CART_PRODUCTs" ThisKey="CART_ID" OtherKey="CART_ID" Type="CART_PRODUCT" />
      <Association Name="USER_CART" Member="USER" ThisKey="USER_ID" OtherKey="USER_ID" Type="USER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ORDER_PRODUCTS" Member="ORDER_PRODUCTs">
    <Type Name="ORDER_PRODUCT">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ORDER_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PRODUCT_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PRODUCT_ORDER_PRODUCT" Member="PRODUCT" ThisKey="PRODUCT_ID" OtherKey="PRODUCT_ID" Type="PRODUCT" IsForeignKey="true" />
      <Association Name="ORDER_ORDER_PRODUCT" Member="ORDER" ThisKey="ORDER_ID" OtherKey="ORDER_ID" Type="ORDER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCTS" Member="PRODUCTs">
    <Type Name="PRODUCT">
      <Column Name="PRODUCT_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TITLE" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PRICE" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="IMAGE_URL" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IMAGE_ID" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TYPE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREATED_AT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PRODUCT_CART_PRODUCT" Member="CART_PRODUCTs" ThisKey="PRODUCT_ID" OtherKey="PRODUCT_ID" Type="CART_PRODUCT" />
      <Association Name="PRODUCT_ORDER_PRODUCT" Member="ORDER_PRODUCTs" ThisKey="PRODUCT_ID" OtherKey="PRODUCT_ID" Type="ORDER_PRODUCT" />
      <Association Name="TYPE_PRODUCT_PRODUCT" Member="TYPE_PRODUCT" ThisKey="TYPE_ID" OtherKey="TYPE_ID" Type="TYPE_PRODUCT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SESSIONS" Member="SESSIONs">
    <Type Name="SESSION">
      <Column Name="sid" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="session" Member="session1" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="expires" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.STAFF" Member="STAFFs">
    <Type Name="STAFF">
      <Column Name="STAFF_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ISADMIN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TYPE_PRODUCTS" Member="TYPE_PRODUCTs">
    <Type Name="TYPE_PRODUCT">
      <Column Name="TYPE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAMETYPE" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="FLAG" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="TYPE_PRODUCT_PRODUCT" Member="PRODUCTs" ThisKey="TYPE_ID" OtherKey="TYPE_ID" Type="PRODUCT" />
    </Type>
  </Table>
  <Table Name="dbo.USERS" Member="USERs">
    <Type Name="USER">
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="RESET_TOKEN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TOKEN_EXPIRATION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="USER_CART" Member="CARTs" ThisKey="USER_ID" OtherKey="USER_ID" Type="CART" />
      <Association Name="USER_ORDER" Member="ORDERs" ThisKey="USER_ID" OtherKey="USER_ID" Type="ORDER" />
    </Type>
  </Table>
  <Table Name="dbo.ORDERS" Member="ORDERs">
    <Type Name="ORDER">
      <Column Name="ORDER_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FEE" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="TRANSPORT_FEE" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="USER_EMAIL" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREATED_AT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ORDER_ORDER_PRODUCT" Member="ORDER_PRODUCTs" ThisKey="ORDER_ID" OtherKey="ORDER_ID" Type="ORDER_PRODUCT" />
      <Association Name="USER_ORDER" Member="USER" ThisKey="USER_ID" OtherKey="USER_ID" Type="USER" IsForeignKey="true" />
    </Type>
  </Table>
</Database>